name: CI/CD

on:
    pull_request: { branches: ["*"] }
    push:
        branches:
            - "+([0-9])?(.{+([0-9]),x}).x"
            - master
        paths-ignore:
            - '**/README.md'


jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          
      - name: Test with pytest
        run: |
          pip3 install pytest
          pytest unit-test.py
          
  release:
        needs: test
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 17

            - run: cp .github/.releaserc.json .
            - run: npm i -g semantic-release @semantic-release/changelog @semantic-release/git
            - run: semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
